# Generated by Django 6.0.1 on 2026-04-22 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_venta_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='numero_documento',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='tickets.ciudad'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='tickets.ciudad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asiento_viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tickets.asientoviaje'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.pasajero'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.viaje'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PAGADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.conductor'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.horario'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ruta'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.vehiculo'),
        ),
    ]
