# Generated by Django 6.0.1 on 2026-01-25 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('hora_llegada_estimada', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería')], max_length=5)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('COMBI', 'Combi'), ('BUS', 'Bus')], max_length=10)),
                ('capacidad', models.PositiveIntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsientoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado')], default='DISPONIBLE', max_length=15)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.asiento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('asiento_viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.asientoviaje')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='tickets.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='tickets.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.vehiculo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta')], max_length=10)),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente'), ('ANULADA', 'Anulada')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.conductor')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.horario')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('VENDIDO', 'Vendido'), ('USADO', 'Usado'), ('ANULADO', 'Anulado')], max_length=10)),
                ('asiento_viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.asientoviaje')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.pasajero')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.venta')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='asientoviaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('vehiculo', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='asientoviaje',
            unique_together={('viaje', 'asiento')},
        ),
    ]
